// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrKUnItI0ueIKz26pFXKjobxb1lKMwLaA',
    appId: '1:743980185951:android:52d0f6bf86d8a84e6bdeea',
    messagingSenderId: '743980185951',
    projectId: 'delievery-app-9e7f8',
    databaseURL: 'https://delievery-app-9e7f8-default-rtdb.firebaseio.com',
    storageBucket: 'delievery-app-9e7f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-axdPdF246DJE104Mp5jTeaOrVLUypnc',
    appId: '1:743980185951:ios:3e1f8d24e60463296bdeea',
    messagingSenderId: '743980185951',
    projectId: 'delievery-app-9e7f8',
    databaseURL: 'https://delievery-app-9e7f8-default-rtdb.firebaseio.com',
    storageBucket: 'delievery-app-9e7f8.appspot.com',
    androidClientId: '743980185951-04kng50q0760ai4kh6n5ttqs9qug5agq.apps.googleusercontent.com',
    iosClientId: '743980185951-7msa39gpvqvf6v3ub2gubg2ljfmpqke5.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDelieveryDomiciliario',
  );
}
